'use client';
import { useEffect, useState, useRef } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { motion, MotionConfig, useReducedMotion } from 'framer-motion';
import { Dialog, DialogPanel, DialogTitle } from '@headlessui/react';
import { Menu, X, Moon, Sun, FileText, Copy, Check, BookOpen } from 'lucide-react';
import { profile, education, projects, teaching, keywords, researchIntroduction, ongoing, publicationMedia } from '@/data/site';
import { asset, validLink } from '@/lib/assets';
import { Publication } from '@/types/publication';
import Media from './Media';
import SocialLinks from './SocialLinks';
const sections=[{title:'About',id:'about'},{title:'Research Interests',id:'research'},{title:'Publications',id:'publications'},{title:'Platforms',id:'projects'},{title:'Teaching',id:'teaching'}];
export function Navbar({detail=false}: {detail?:boolean}) {
 const [open,setOpen]=useState(false);const [dark,setDark]=useState(true);const [active,setActive]=useState('about');
 useEffect(()=>{let preference=null;try{preference=localStorage.getItem('academic-theme');}catch{} const d=preference!=='light';setDark(d);document.documentElement.classList.toggle('dark',d);
 const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)setActive(e.target.id);});},{rootMargin:'-15% 0px -65% 0px'});document.querySelectorAll('main section[id]').forEach(e=>observer.observe(e));return()=>observer.disconnect();},[]);
 const toggle=()=>{const d=!dark;setDark(d);document.documentElement.classList.toggle('dark',d);try{localStorage.setItem('academic-theme',d?'dark':'light');}catch{}};
 return <header className="nav-shell"><nav className="nav container" aria-label="Main navigation"><Link className="brand" href="/">ASY<span> / RESEARCH</span></Link><div className={`nav-links ${open?'open':''}`}>{sections.map(s=><Link key={s.id} href={`${detail?'/':''}#${s.id}`} className={active===s.id?'active':''} onClick={()=>setOpen(false)}>{s.title}</Link>)}{validLink(profile.cv)&&<a href={asset(profile.cv)}>CV</a>}</div><div className="nav-actions"><button onClick={toggle} className="icon-button" aria-label={dark?'Switch to light mode':'Switch to dark mode'}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="icon-button menu" aria-expanded={open} aria-label="Toggle navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></nav></header>;
}
export function Reveal({children,className=''}: {children:React.ReactNode;className?:string}) {const reduce=useReducedMotion();return <motion.div className={className} initial={reduce?false:{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:.45}}>{children}</motion.div>;}
export function SectionHeading({number,title,subtitle}: {number:string;title:string;subtitle?:string}) {return <div className="section-heading"><div><span className="eyebrow">{number} / {title.toUpperCase()}</span><h2>{title}</h2></div>{subtitle&&<p>{subtitle}</p>}</div>;}
export function PublicationCard({pub}: {pub:Publication}) {
 const [open,setOpen]=useState(false);const [copied,setCopied]=useState(false);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 const media=publicationMedia[pub.id]; const links=media?.links ?? [{label:'Paper',url:pub.url||''},{label:'Code',url:pub.code||''}];
 return <article className="publication-card"><Media title={pub.title} image={media?.image||pub.preview} video={media?.video}/><div className="publication-body"><div className="pub-meta"><span>{pub.conference||pub.journal||'Venue to be confirmed'} · {pub.year}</span><span className="pill">{pub.status==='accepted'?'Accepted':pub.status}</span></div><h3>{pub.title}</h3><p className="authors">{pub.authors.some(a=>a.name.includes('TODO'))?'Author list to be confirmed':pub.authors.map(a=>a.name).join(', ')}</p><p>{pub.description?.replace(/TODO_\w+/g,'').trim()}</p><div className="pub-links">{links.filter(l=>validLink(l.url)).map(l=><a key={l.label} href={asset(l.url)} target="_blank" rel="noreferrer">{l.label}</a>)}{pub.bibtex&&<button onClick={()=>{setOpen(true);setCopied(false);}}><FileText size={15}/> BibTeX</button>}</div></div>
 <Dialog open={open} onClose={()=>setOpen(false)} className="dialog"><div className="dialog-backdrop"/><div className="dialog-wrap"><DialogPanel className="dialog-panel"><div className="dialog-head"><DialogTitle>Bibliographic record</DialogTitle><button className="icon-button" aria-label="Close BibTeX" onClick={()=>setOpen(false)}><X/></button></div>{pub.bibtex?.includes("TODO") && <p>This record contains TODO fields. Confirm the title and author order before citing.</p>}<pre>{pub.bibtex}</pre><button className="button" onClick={async()=>{try{await navigator.clipboard.writeText(pub.bibtex!);setCopied(true);timer.current=setTimeout(()=>setCopied(false),2200);}catch{setCopied(false);}}}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Copied':'Copy BibTeX'}</button></DialogPanel></div></Dialog></article>;
}
export function Footer(){return <footer className="container footer"><span>Ali Sidar Yilmaz <span className="muted">/ Aerial Robotics</span></span><span>Built on <a href="https://github.com/xyjoey/PRISM">PRISM</a></span><a href="#about">Back to top</a></footer>;}
export default function AcademicSite({publications}: {publications:Publication[]}) {
 return <MotionConfig reducedMotion="user"><Navbar/><main>
 <section id="about" className="hero container"><Reveal className="hero-copy"><div className="eyebrow">AERIAL ROBOTICS · DYNAMICS · CONTROL</div><h1>Ali Sidar Yilmaz<span className="name-dot">.</span></h1><p className="hero-role">PhD Candidate at <a href="https://www.tum.de/en/">Technical University of Munich</a></p><div className="hero-biography"><p>I am a PhD candidate at the <a href={profile.labUrl}>Autonomous Aerial Systems Lab</a> at TUM, supervised by <a href={profile.supervisorUrl}>Prof. Dr. Markus Ryll</a>.</p><p>I hold a BSc in Aerospace Engineering from <a href={education[0].url}>Middle East Technical University (METU)</a> and an MSc in Aerospace from <a href={education[1].url}>TUM</a>.</p><p>My research focuses on developing a generalized control approach for aerial physical interaction. Learn more about my <a href="#research">research interests</a> and <a href="#publications">publications</a>.</p></div><SocialLinks/></Reveal>
 <Reveal className="hero-portrait"><Image src={asset(profile.portrait)} alt="Ali Sidar Yilmaz" width={640} height={641} priority sizes="(max-width: 760px) 260px, 320px"/>{validLink(profile.cv)&&<a className="portrait-cv text-link" href={asset(profile.cv)}><FileText size={17}/> Resume / CV</a>}</Reveal>
 <Reveal className="education-row">{education.map(e=><a className="education-entry" key={`${e.abbreviation}-${e.degree}`} href={e.url}><div className="education-logo"><Image className="university-logo logo-light" src={asset(e.logo)} alt={`${e.abbreviation} logo`} width={200} height={100}/><Image className="university-logo logo-dark" src={asset(e.darkLogo)} alt={`${e.abbreviation} logo`} width={200} height={100}/></div><strong>{e.degree}</strong><span>{e.field}</span><span className="education-school">{e.school}</span>{e.period&&<small>{e.period}</small>}</a>)}</Reveal>
 </section><div className="research-strip"><div className="container"><span>AERIAL ROBOTICS</span><div className="keyword-list">{keywords.map(k=><span key={k}>{k}</span>)}</div></div></div>
 <section id="research" className="container section research-interests"><SectionHeading number="01" title="Research Interests" subtitle="A generalized control approach for aerial physical interaction."/><Reveal className="research-introduction">{researchIntroduction.map(p=><p key={p}>{p}</p>)}</Reveal><div className="interest-media"><figure><Media title="Xwebun interacting with a contact test fixture" image="/media/projects/xwebun-contact.jpg"/><figcaption>Aerial physical interaction and constraint estimation on Xwebun.</figcaption></figure><figure><Media title="SMORS soft aerial platform with rigid and compliant rotor arms" image="/media/projects/smors-prototype.jpg"/><figcaption>SMORS: mechanical compliance and fully actuated aerial motion.</figcaption></figure></div></section>
 <section id="publications" className="publication-section"><div className="container section"><SectionHeading number="02" title="Publications" subtitle="Experimental research in dynamics, estimation, and control."/>{publications.map(pub=><Reveal key={pub.id}><PublicationCard pub={pub}/></Reveal>)}</div></section>
 <section id="projects" className="container section"><SectionHeading number="03" title="Experimental platforms" subtitle="Research grounded in real aerial systems."/><div className="project-grid">{projects.map(p=><Reveal key={p.title}><article className="project-card"><Media title={p.title} image={p.image} video={p.video} kind={p.kind}/><p className="platform-caption">{p.caption}</p><div className="card-content"><span className="eyebrow">{p.label}</span><h3>{p.title}</h3><p>{p.summary}</p><Link className="text-link" href={`/research/${p.slug}/`}>Related research</Link></div></article></Reveal>)}</div><div className="ongoing-heading">Further research</div><div className="ongoing-grid">{ongoing.map(p=><article className="ongoing-card" key={p.title}><span className="eyebrow">RESEARCH TOPIC</span><h3>{p.title}</h3><p>{p.summary}</p></article>)}</div></section>
 <section id="teaching" className="container section compact-section"><SectionHeading number="04" title="Teaching"/><div className="teaching-list">{teaching.map(t=><Reveal key={t.title}><article className="teaching-card"><span className="course-icon"><BookOpen size={25}/></span><div><span className="eyebrow">{t.label}</span><h3>{t.title}</h3><p>{t.summary}</p></div></article></Reveal>)}</div></section>
 <section id="contact" className="container contact-section"><div><span className="eyebrow">CONTACT</span><h2>Let’s connect.</h2><p>{profile.role}<br/>{profile.institution}</p></div><div><p>For research enquiries, please use my work email.</p><SocialLinks/></div></section>
 </main><Footer/></MotionConfig>;
}
